Support Adding an item to the cart
Deepak-Testpress/shopping_app pull request #7
Opened 2022-11-21 05:09 UTC by Deepak-Testpress

2022-11-24 09:37 UTC, waranlogesh requested changes

2022-11-29 09:36 UTC, Deepak-Testpress commented on myshop/tests/cart/test_cart.py
> +    def test_change_product_quantity_adds_product_to_cart_with_quantity_when_product_not_already_exists_in_cart(
Changed in the previous PR

2022-11-29 09:37 UTC, Deepak-Testpress commented on myshop/cart/views.py
> +    product = get_object_or_404(Product, id=product_id)
Added test cases for cart_add method here

2022-11-29 09:37 UTC, Deepak-Testpress commented on myshop/tests/cart/test_forms.py
> +    def test_cart_add_product_validates_false_with_quantity_undervalue_choice_range(
Renamed

2022-11-29 09:37 UTC, Deepak-Testpress commented on myshop/tests/cart/test_forms.py
> +    def test_cart_add_product_validates_false_with_quantity_exceeding_choice_range(
Renamed

2022-11-29 09:37 UTC, Deepak-Testpress commented on myshop/tests/cart/test_forms.py
> +    def test_cart_add_product_validates_true_with_quantity_not_exceeding_choice_range(
Renamed

2022-11-29 09:49 UTC, waranlogesh approved these changes

2022-12-02 12:59 UTC, merged